#!/usr/bin/env python3
"""
Purpose: 安全 HTTP 客户端工具 v2 — 为安全测试脚本提供统一的 HTTP 请求封装
         支持：请求重试、代理、速率限制、SSL 控制、请求/响应日志、
              请求历史回放、WAF 检测、批量请求、异步模式
Auth: 仅限授权安全测试使用
Dependencies: requests, urllib3, httpx (可选, 异步支持)
Usage:
    from http_client import SecureHttpClient, ClientConfig

    # 同步模式
    client = SecureHttpClient(proxy="http://127.0.0.1:8080", rate_limit=2.0)
    resp = client.get("https://target/api", params={"id": 1})

    # 异步模式
    async with SecureHttpClient.async_client() as client:
        resp = await client.aget("https://target/api")

    # 批量请求
    results = client.batch_get(["https://t1.com", "https://t2.com"], concurrency=10)

    # WAF 检测
    waf_info = client.detect_waf("https://target.com")
"""

import asyncio
import logging
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple
from urllib.parse import urlparse

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

logger = logging.getLogger("SecureHttpClient")


@dataclass
class RequestRecord:
    """请求历史记录"""
    method: str
    url: str
    status_code: int
    elapsed_ms: float
    request_headers: Dict[str, str]
    request_body: Optional[str]
    response_headers: Dict[str, str]
    response_body_preview: str  # 前 500 字符
    timestamp: float


@dataclass
class WAFDetection:
    """WAF 检测结果"""
    detected: bool
    vendor: Optional[str]
    confidence: float  # 0.0 - 1.0
    indicators: List[str]
    block_status_codes: List[int]


@dataclass
class ClientConfig:
    """客户端配置"""
    timeout: int = 10
    verify_ssl: bool = False
    proxy: Optional[str] = None
    user_agent: str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    rate_limit: float = 0.0              # 每秒最大请求数，0 = 不限速
    retries: int = 2
    retry_backoff: float = 0.5
    retry_status_codes: tuple = (500, 502, 503, 504)
    cookies: Optional[Dict[str, str]] = None
    headers: Optional[Dict[str, str]] = None
    follow_redirects: bool = True
    max_redirects: int = 5
    log_requests: bool = False
    history_size: int = 100              # 请求历史最大条数
    history_body_preview: int = 500      # 响应体预览长度


# WAF 指纹库（精简版，完整版见 waf_bypass_tester.py）
WAF_FINGERPRINTS: Dict[str, Dict] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "block_codes": [403, 503],
        "block_body": ["attention required", "cloudflare ray id"],
        "confidence": 0.95,
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "block_codes": [403],
        "block_body": ["the request could not be satisfied", "forbidden"],
        "confidence": 0.9,
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop"],
        "block_codes": [403],
        "block_body": ["access denied", "reference #"],
        "confidence": 0.9,
    },
    "imperva": {
        "headers": ["x-iinfo", "x-cdn"],
        "block_codes": [403],
        "block_body": ["the incident id", "imperva"],
        "confidence": 0.85,
    },
    "modsecurity": {
        "headers": ["server: apache"],
        "block_codes": [403, 501],
        "block_body": ["modsecurity", "not acceptable", "this error was generated by mod_security"],
        "confidence": 0.9,
    },
    "f5_asm": {
        "headers": ["x-waf-event", "server: bigip"],
        "block_codes": [403],
        "block_body": ["the requested url was rejected", "please consult with your administrator"],
        "confidence": 0.85,
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "server: sucuri"],
        "block_codes": [403],
        "block_body": ["access denied", "sucuri website firewall"],
        "confidence": 0.9,
    },
    "wordfence": {
        "headers": ["x-wordfence"],
        "block_codes": [403, 503],
        "block_body": ["generated by wordfence", "your access to this site has been limited"],
        "confidence": 0.9,
    },
    "fortiweb": {
        "headers": ["server: fortiweb"],
        "block_codes": [403],
        "block_body": ["blocked by fortiweb"],
        "confidence": 0.9,
    },
}


class SecureHttpClient:
    """
    安全测试 HTTP 客户端 v2
    
    特性：
    - 自动重试（可配置状态码和退避策略）
    - 速率限制（令牌桶算法）
    - 代理支持（Burp/ZAP 集成）
    - SSL 验证控制
    - 请求/响应日志
    - 请求历史记录与回放
    - WAF 检测
    - 批量请求
    - 上下文管理器
    """

    def __init__(self, config: Optional[ClientConfig] = None, **kwargs):
        if config is None:
            config = ClientConfig(**kwargs)
        self.config = config
        self.session = requests.Session()
        self._last_request_time: float = 0
        self._request_count: int = 0
        self._history: deque[RequestRecord] = deque(maxlen=config.history_size)
        self._setup_session()

    def _setup_session(self):
        """配置 requests Session"""
        retry_strategy = Retry(
            total=self.config.retries,
            backoff_factor=self.config.retry_backoff,
            status_forcelist=self.config.retry_status_codes,
            allowed_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"],
        )
        adapter = HTTPAdapter(max_retries=retry_strategy)
        self.session.mount("http://", adapter)
        self.session.mount("https://", adapter)
        self.session.verify = self.config.verify_ssl
        self.session.headers.update({"User-Agent": self.config.user_agent})

        if self.config.proxy:
            self.session.proxies = {"http": self.config.proxy, "https": self.config.proxy}
        if self.config.cookies:
            self.session.cookies.update(self.config.cookies)
        if self.config.headers:
            self.session.headers.update(self.config.headers)
        self.session.max_redirects = self.config.max_redirects

    def _rate_limit_wait(self):
        """速率限制等待（令牌桶）"""
        if self.config.rate_limit <= 0:
            return
        min_interval = 1.0 / self.config.rate_limit
        elapsed = time.time() - self._last_request_time
        if elapsed < min_interval:
            time.sleep(min_interval - elapsed)
        self._last_request_time = time.time()

    def _record(self, method: str, url: str, resp: requests.Response,
                req_headers: Dict, req_body: Optional[str]):
        """记录请求历史"""
        try:
            body_preview = resp.text[:self.config.history_body_preview]
        except Exception:
            body_preview = "<binary>"
        record = RequestRecord(
            method=method, url=url,
            status_code=resp.status_code,
            elapsed_ms=resp.elapsed.total_seconds() * 1000,
            request_headers=dict(req_headers) if req_headers else {},
            request_body=req_body,
            response_headers=dict(resp.headers),
            response_body_preview=body_preview,
            timestamp=time.time(),
        )
        self._history.append(record)

    # ----------------------------------------------------------
    # 核心 HTTP 方法
    # ----------------------------------------------------------

    def request(self, method: str, url: str, **kwargs) -> requests.Response:
        """发送 HTTP 请求"""
        self._rate_limit_wait()
        self._request_count += 1
        kwargs.setdefault("timeout", self.config.timeout)
        kwargs.setdefault("allow_redirects", self.config.follow_redirects)

        if self.config.log_requests:
            logger.debug(f"[{self._request_count}] {method} {url}")

        resp = self.session.request(method, url, **kwargs)
        self._record(method, url, resp,
                     kwargs.get("headers", self.session.headers),
                     kwargs.get("data") or kwargs.get("json"))
        return resp

    def get(self, url: str, **kwargs) -> requests.Response:
        return self.request("GET", url, **kwargs)

    def post(self, url: str, **kwargs) -> requests.Response:
        return self.request("POST", url, **kwargs)

    def put(self, url: str, **kwargs) -> requests.Response:
        return self.request("PUT", url, **kwargs)

    def delete(self, url: str, **kwargs) -> requests.Response:
        return self.request("DELETE", url, **kwargs)

    def head(self, url: str, **kwargs) -> requests.Response:
        return self.request("HEAD", url, **kwargs)

    def options(self, url: str, **kwargs) -> requests.Response:
        return self.request("OPTIONS", url, **kwargs)

    # ----------------------------------------------------------
    # 增强功能
    # ----------------------------------------------------------

    def send_with_variations(self, method: str, url: str,
                             param_name: str, param_value: str,
                             variations: Optional[List[str]] = None) -> List[Tuple[str, requests.Response]]:
        """
        发送同一请求的多种变体（用于注入测试）

        Args:
            method: HTTP 方法
            url: 目标 URL
            param_name: 参数名
            param_value: 原始值
            variations: 变体列表（None 则使用原始值）

        Returns:
            [(variation, response), ...]
        """
        results = []
        targets = variations or [param_value]
        for var in targets:
            parsed = urlparse(url)
            if parsed.query:
                # URL 已有查询参数，附加
                sep = "&"
            else:
                sep = "?"
            test_url = f"{url}{sep}{param_name}={var}" if "?" not in url or sep == "&" else url

            # 也支持 POST body
            try:
                resp = self.request(method, test_url)
                results.append((var, resp))
            except requests.RequestException as e:
                logger.warning(f"Variation '{var}' failed: {e}")
                results.append((var, None))
        return results

    def get_with_retry(self, url: str, max_attempts: int = 3, **kwargs) -> requests.Response:
        """带手动重试的 GET（适用于不稳定目标）"""
        last_exc = None
        for i in range(max_attempts):
            try:
                return self.get(url, **kwargs)
            except requests.RequestException as e:
                last_exc = e
                wait = self.config.retry_backoff * (2 ** i)
                logger.warning(f"Attempt {i+1}/{max_attempts} failed: {e}, retrying in {wait}s")
                time.sleep(wait)
        raise last_exc

    def baseline(self, url: str, method: str = "GET", **kwargs) -> Dict[str, Any]:
        """
        获取基准响应（用于盲注/布尔注入的对比）

        Returns:
            {"status": int, "length": int, "headers": dict, "body": str, "time_ms": float}
        """
        resp = self.request(method, url, **kwargs)
        return {
            "status": resp.status_code,
            "length": len(resp.text),
            "headers": dict(resp.headers),
            "body": resp.text,
            "time_ms": resp.elapsed.total_seconds() * 1000,
        }

    def compare_with_baseline(self, baseline: Dict, resp: requests.Response,
                              threshold: float = 0.1) -> Dict[str, Any]:
        """
        将响应与基准对比（用于检测注入引起的差异）

        Args:
            baseline: baseline() 返回的字典
            resp: 待对比的响应
            threshold: 长度差异阈值（比例）

        Returns:
            {"status_changed": bool, "length_changed": bool, "time_changed": bool, "diff_ratio": float}
        """
        curr_len = len(resp.text)
        base_len = baseline["length"]
        diff_ratio = abs(curr_len - base_len) / max(base_len, 1)

        return {
            "status_changed": resp.status_code != baseline["status"],
            "length_changed": diff_ratio > threshold,
            "length_diff_ratio": diff_ratio,
            "time_changed": abs(resp.elapsed.total_seconds() * 1000 - baseline["time_ms"]) > 2000,
            "response": resp,
        }

    # ----------------------------------------------------------
    # WAF 检测
    # ----------------------------------------------------------

    def detect_waf(self, url: str) -> WAFDetection:
        """
        检测目标是否部署了 WAF

        使用无害的请求头变化来探测，不发送攻击 payload。
        """
        indicators = []
        vendor = None
        confidence = 0.0
        block_codes = []

        try:
            # 正常请求
            resp = self.get(url)
            resp_headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
            resp_body = resp.text.lower()

            for waf_vendor, sig in WAF_FINGERPRINTS.items():
                score = 0.0
                matched = []

                # 检查响应头
                for hdr_pattern in sig["headers"]:
                    if ":" in hdr_pattern:
                        k, v = hdr_pattern.split(":", 1)
                        if k.strip().lower() in resp_headers and v.strip() in resp_headers[k.strip().lower()]:
                            score += 0.4
                            matched.append(f"header:{hdr_pattern}")
                    else:
                        if any(hdr_pattern.lower() in k for k in resp_headers):
                            score += 0.3
                            matched.append(f"header:{hdr_pattern}")

                # 检查状态码（仅对可疑状态码）
                if resp.status_code in sig.get("block_codes", []):
                    score += 0.1

                if score > confidence:
                    confidence = score
                    vendor = waf_vendor
                    indicators = matched

        except requests.RequestException as e:
            logger.warning(f"WAF detection failed: {e}")

        return WAFDetection(
            detected=confidence > 0.3,
            vendor=vendor,
            confidence=min(confidence, 1.0),
            indicators=indicators,
            block_codes=block_codes,
        )

    # ----------------------------------------------------------
    # 批量请求
    # ----------------------------------------------------------

    def batch_get(self, urls: List[str], concurrency: int = 5,
                  callback: Optional[Callable] = None) -> List[Tuple[str, Optional[requests.Response]]]:
        """
        批量 GET 请求（线程池并发）

        Args:
            urls: URL 列表
            concurrency: 最大并发数
            callback: 可选回调 (url, response) -> None

        Returns:
            [(url, response), ...]
        """
        from concurrent.futures import ThreadPoolExecutor, as_completed

        results = []
        with ThreadPoolExecutor(max_workers=concurrency) as executor:
            future_to_url = {executor.submit(self.get, url): url for url in urls}
            for future in as_completed(future_to_url):
                url = future_to_url[future]
                try:
                    resp = future.result()
                    results.append((url, resp))
                    if callback:
                        callback(url, resp)
                except Exception as e:
                    results.append((url, None))
                    logger.warning(f"Batch GET {url} failed: {e}")
        return results

    # ----------------------------------------------------------
    # 请求历史
    # ----------------------------------------------------------

    @property
    def history(self) -> List[RequestRecord]:
        """获取请求历史"""
        return list(self._history)

    def replay_last(self, modifications: Optional[Dict] = None) -> requests.Response:
        """
        回放最近一次请求（可选修改）

        Args:
            modifications: {"method": str, "url": str, "headers": dict, "body": str}

        Returns:
            requests.Response
        """
        if not self._history:
            raise ValueError("No request history to replay")

        last = self._history[-1]
        method = (modifications or {}).get("method", last.method)
        url = (modifications or {}).get("url", last.url)
        headers = (modifications or {}).get("headers", last.request_headers)
        body = (modifications or {}).get("body", last.request_body)

        return self.request(method, url, headers=headers, data=body)

    def export_history_curl(self) -> List[str]:
        """导出请求历史为 curl 命令"""
        commands = []
        for rec in self._history:
            parts = [f"curl -X {rec.method}"]
            for k, v in rec.request_headers.items():
                if k.lower() not in ("host", "connection", "content-length"):
                    parts.append(f"-H '{k}: {v}'")
            if rec.request_body:
                parts.append(f"-d '{rec.request_body}'")
            parts.append(f"'{rec.url}'")
            commands.append(" ".join(parts))
        return commands

    # ----------------------------------------------------------
    # 状态信息
    # ----------------------------------------------------------

    @property
    def request_count(self) -> int:
        return self._request_count

    def get_cookies(self) -> Dict[str, str]:
        return dict(self.session.cookies)

    def close(self):
        self.session.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    def __repr__(self):
        return (f"SecureHttpClient(requests={self._request_count}, "
                f"history={len(self._history)}, proxy={self.config.proxy})")


# ============================================================
# 异步 HTTP 客户端（可选，需要 httpx）
# ============================================================

class AsyncSecureHttpClient:
    """
    异步安全 HTTP 客户端
    
    需要: pip install httpx
    """

    def __init__(self, config: Optional[ClientConfig] = None, **kwargs):
        try:
            import httpx
        except ImportError:
            raise ImportError("异步模式需要 httpx: pip install httpx")

        if config is None:
            config = ClientConfig(**kwargs)
        self.config = config
        self._client: Optional[httpx.AsyncClient] = None

    async def __aenter__(self):
        import httpx
        self._client = httpx.AsyncClient(
            timeout=self.config.timeout,
            verify=self.config.verify_ssl,
            proxy=self.config.proxy,
            follow_redirects=self.config.follow_redirects,
            headers={"User-Agent": self.config.user_agent},
            limits=httpx.Limits(max_connections=50, max_keepalive_connections=20),
        )
        return self

    async def __aexit__(self, *args):
        if self._client:
            await self._client.aclose()

    async def aget(self, url: str, **kwargs):
        return await self._client.get(url, **kwargs)

    async def apost(self, url: str, **kwargs):
        return await self._client.post(url, **kwargs)

    async def abatch_get(self, urls: List[str], concurrency: int = 20):
        """异步批量 GET"""
        import asyncio
        semaphore = asyncio.Semaphore(concurrency)

        async def _fetch(url):
            async with semaphore:
                try:
                    resp = await self.aget(url)
                    return (url, resp)
                except Exception as e:
                    return (url, None)

        return await asyncio.gather(*[_fetch(u) for u in urls])


# ============================================================
# 工厂函数
# ============================================================

def create_burp_client(port: int = 8080) -> SecureHttpClient:
    """创建 Burp Suite 代理客户端"""
    return SecureHttpClient(
        proxy=f"http://127.0.0.1:{port}",
        rate_limit=5.0,
        verify_ssl=False,
        log_requests=True,
    )


def create_scanner_client(rate_limit: float = 10.0, concurrency: int = 5) -> SecureHttpClient:
    """创建扫描器客户端（高并发、限速）"""
    return SecureHttpClient(
        rate_limit=rate_limit,
        retries=1,
        timeout=5,
        log_requests=False,
    )
